// list of Morse code representations for letters and numbers (not complete set)
const jumpList = {
  "a": ".-",
  "b": "-...",
  "c": "-.-.",
  "d": "-..",
  "e": ".",
  "f": "..-.",
  "g": "--.",
  "h": "....",
  "i": "..",
  "j": ".---",
  "k": "-.--",
  "l": ".-..",
  "m": "--",
  "n": "-.",
  "o":  "---",
  "p": ".--.",
  "q": "--.-",
  "r": ".-.",
  "s": "...",
  "t": "-",
  "u": "..-",
  "v": "...-",
  "w": ".--",
  "x": "-..-",
  "y": "-.--",
  "z": "--..",
  "1": ".----",
  "2": "..---",
  "3": "...--",
  "4": "....-",
  "5": ".....",
  "6": "-....",
  "7": "--...",
  "8": "---..",
  "9": "----.",
  "0": "-----",
  ".": ".-.-.-",
  ",": "--..--",
  "?": "..--..",
  "'": ".----.",
  "!": "..--.",
  ":": "---...",
  "-": "-....-",
  "/": "-..-.",
  "(": "-.--.",
  "= ": "-...-",
};

// This function converts a string of text into Morse code.
function morseCodeConv() {
    input = document.getElementById("morseCodeOutput").value;
    document.getElementById("morseCodeText").value = input;
}